use SHU_UNIVER
--1-2
select AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY, AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM inner join AUDITORIUM_TYPE	
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 
and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%מלןü‏עונ%'
--3
select A.AUDITORIUM, A.AUDITORIUM_TYPE, 
A.AUDITORIUM_CAPACITY, A.AUDITORIUM_NAME, AT.AUDITORIUM_TYPENAME
from AUDITORIUM as A, AUDITORIUM_TYPE as AT
where A.AUDITORIUM_TYPE = AT.AUDITORIUM_TYPE
--4-5
select  FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION_NAME, STUDENT.NAME, SUBJECT.SUBJECT_NAME, PROGRESS.NOTE,
case
when (PROGRESS.NOTE = 6) then 'רוסעü'
when (PROGRESS.NOTE = 7) then 'סולü'
when (PROGRESS.NOTE = 8) then 'גמסולü'
end [NOTE]
from FACULTY 
inner join PULPIT
	on FACULTY.FACULTY = PULPIT.FACULTY
inner join PROFESSION
	on PULPIT.FACULTY = PROFESSION.FACULTY
inner join SUBJECT
	on SUBJECT.PULPIT = PULPIT.PULPIT
inner join PROGRESS
	on PROGRESS.SUBJECT = SUBJECT.SUBJECT
inner join STUDENT
	on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT AND PROGRESS.NOTE BETWEEN 6 and 8
ORDER BY PROGRESS.NOTE DESC
--6
select isnull(TEACHER.TEACHER_NAME,'***')[Teacher], PULPIT.PULPIT
from PULPIT left outer join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT
--7
select  PULPIT.PULPIT, isnull(TEACHER.TEACHER_NAME,'***')[Teacher]
from TEACHER left outer join PULPIT
on PULPIT.PULPIT = TEACHER.PULPIT
--8
SELECT * FROM AUDITORIUM full OUTER JOIN AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT * FROM AUDITORIUM left OUTER JOIN AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT * FROM AUDITORIUM right OUTER JOIN AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT * FROM AUDITORIUM inner JOIN AUDITORIUM_TYPE
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
--9
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM cross JOIN AUDITORIUM_TYPE
where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
